/*#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code generated by Luke                                                             *///
void driveForward(int x){
	int rx,lx=x;
	SensorValue[leftDriveEnc]=0;
	SensorValue[rightDriveEnc]=0;

	while(rx>0||lx>0){
		motor[FrontLeft]=motor[BackLeft]=lx*20;
		motor[FrontRight]=motor[BackRight]=rx*20;
		lx-=abs((SensorValue[leftDriveEnc]/360)*(int)(3.1415926*(float)(4)));
		rx-=abs((SensorValue[leftDriveEnc]/360)*(int)(3.1415926*(float)(4)));
	}
}
void driveBackwards(int x){
	int rx,lx=x;
	SensorValue[leftDriveEnc]=0;
	SensorValue[rightDriveEnc]=0;

	while(rx>0||lx>0){
		motor[FrontLeft]=motor[BackLeft]=-lx*20;
		motor[FrontRight]=motor[BackRight]=-rx*20;
		lx-=abs((SensorValue[leftDriveEnc]/360)*(int)(3.1415926*(float)(4)));
		rx-=abs((SensorValue[leftDriveEnc]/360)*(int)(3.1415926*(float)(4)));
	}
}
task auton()
{
driveForward(40);
wait1Msec(1425);
driveBackwards(72);
wait1Msec(2085);
motor[FrontLeft]=motor[BackLeft]=80;
motor[FrontRight]=motor[BackRight]=80;
wait1Msec(535);
motor[FrontLeft]=motor[BackLeft]=0;
motor[FrontRight]=motor[BackRight]=0;
driveForward(40);


}
