/*#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code generated by Luke                                                             *///

task drive(){while(true)
{
		int c1=vexRT[Ch1];
		int c2=vexRT[Ch2];
		int c3=vexRT[Ch3];
		int c4=vexRT[Ch4];

		//Deadzones
		if(abs(c1)<20){c1=0;}
		if(abs(c2)<20){c2=0;}
		if(abs(c3)<20){c3=0;}
		if(abs(c4)<20){c4=0;}

		//Drivetrain
		motor[FrontLeft]=motor[BackLeft]=c3;
		motor[FrontRight]=motor[BackRight]=-c2;

		//Intake
		if(vexRT[Btn5U]){
			motor[Intake]=127;
		}
		if(vexRT[Btn5D]){
			motor[Intake]=-127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			motor[Intake]=0;
		}

		//Flipper
		if(vexRT[Btn6U]){
			motor[Flipper]=63;
		}
		if(vexRT[Btn6D]){
			motor[Flipper]=-63;
		}
		if(!vexRT[Btn6U]&&!vexRT[Btn6D]){
			motor[Flipper]=0;
		}

		//Launcher
		if(vexRT[Btn7U]){
			motor[Launcher]=127;
		}
		/*if(vexRT[Btn7D]){
			motor[Launcher]=-127;
		}*/
		if(!vexRT[Btn7U]&&!vexRT[Btn7D]){
			motor[Launcher]=0;
		}

		//Fourbar
		if(vexRT[Btn8U]){
			motor[FourBar]=127;
		}
		if(vexRT[Btn8D]){
			motor[FourBar]=-127;
		}
		if(!vexRT[Btn8U]&&!vexRT[Btn8D]){
			motor[FourBar]=0;
		}
}}
