/*#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           TopFlyWheel,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           BottomFlyWheel,tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code generated by Luke                                                             *///
int systemTimer=0;
int flyWheelTimer=0;
int flyWheelInitialPos=0;
int flyWheelInitialTime=0;
int flyWheelAvgVelocity=0;
char buffer[5];
void flyWheelSlewUp(int seconds){
	if(motor[leftFlyWheel]<127){
	for(int x = 0; x<=seconds*10; x++){
	motor[leftFlyWheel]+=(127/(seconds*10));
	motor[rightFlyWheel]-=(127/(seconds*10));
	wait1Msec(100);
	int c2=vexRT[Ch2];
	int c3=vexRT[Ch3];
	if(abs(c2)<20){c2=0;}
	if(abs(c3)<20){c3=0;}
	motor[FrontLeft]=motor[BackLeft]=c3;
	motor[FrontRight]=motor[BackRight]=-c2;
	if(vexRT[Btn5U]){
			motor[Intake]=127;
		}
		if(vexRT[Btn5D]){
			motor[Intake]=-127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			motor[Intake]=0;
		}
	}
}
motor[leftFlyWheel]=127;
motor[rightFlyWheel]=-127;
}

void flyWheelSlewDown(int seconds){
	if(motor[leftFlyWheel]>0){
	for(int x = 0; x<=seconds*10; x++){
	motor[leftFlyWheel]-=(127/(seconds*10));
	motor[rightFlyWheel]+=(127/(seconds*10));
	wait1Msec(100);
	int c2=vexRT[Ch2];
	int c3=vexRT[Ch3];
	if(abs(c2)<20){c2=0;}
	if(abs(c3)<20){c3=0;}
	motor[FrontLeft]=motor[BackLeft]=c3;
	motor[FrontRight]=motor[BackRight]=-c2;
	if(vexRT[Btn5U]){
			motor[Intake]=127;
		}
		if(vexRT[Btn5D]){
			motor[Intake]=-127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			motor[Intake]=0;
		}
	}
}
motor[leftFlyWheel]=0;
motor[rightFlyWheel]=0;
}

task drive(){while(true)
{
	systemTimer=nSysTime;
	flyWheelInitialPos=SensorValue[flyWheelEnc];
	flyWheelInitialTime=nSysTime;
		//Variable Init

		//Ints
		int spinUpTime = 5;
		int spinDownTime = 7;
		int c1=vexRT[Ch1];
		int c2=vexRT[Ch2];
		int c3=vexRT[Ch3];
		int c4=vexRT[Ch4];

		//Deadzones
		if(abs(c1)<20){c1=0;}
		if(abs(c2)<20){c2=0;}
		if(abs(c3)<20){c3=0;}
		if(abs(c4)<20){c4=0;}

		//Drivetrain
		motor[FrontLeft]=motor[BackLeft]=c3;
		motor[FrontRight]=motor[BackRight]=-c2;

		//Flipper
		if(vexRT[Btn6U]){
			motor[Flipper]=127;
		}
		if(vexRT[Btn6D]){
			motor[Flipper]=-127;
		}
		if(!vexRT[Btn6U]&&!vexRT[Btn6D]){
			motor[Flipper]=0;
		}

		//Intake
		if(vexRT[Btn5U]){
			motor[Intake]=127;
		}
		if(vexRT[Btn5D]){
			motor[Intake]=-127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			motor[Intake]=0;
		}

		//Flywheel
		if(vexRT[Btn8U] && (nSysTime-flyWheelTimer)>spinDownTime){
			flyWheelSlewUp(spinUpTime);
			flyWheelTimer=nSysTime;
		}
		if(vexRT[Btn8D] && (nSysTime-flyWheelTimer)>spinUpTime){
			flyWheelSlewDown(spinDownTime);
			flyWheelTimer=nSysTime;
		}
		flyWheelAvgVelocity=(flyWheelEnc-flyWheelInitialPos)/(nSysTime-flyWheelInitialTime);
		sprintf(buffer, "%d",flyWheelAvgVelocity);
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDString(0,0, buffer);
		wait1Msec(25-(nSysTime-systemTimer));
}}
