/*#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code generated by Luke                                                             *///

	int flipTime=0;
	int barTime=0;
	bool flipToggle = false;
	bool barToggle = false;

task drive(){while(true)
{


		int c1=vexRT[Ch1];
		int c2=vexRT[Ch2];
		int c3=vexRT[Ch3];
		int c4=vexRT[Ch4];

		//Deadzones
		if(abs(c1)<20){c1=0;}
		if(abs(c2)<20){c2=0;}
		if(abs(c3)<20){c3=0;}
		if(abs(c4)<20){c4=0;}

		//Drivetrain
		motor[FrontLeft]=motor[BackLeft]=c3;
		motor[FrontRight]=motor[BackRight]=-c2;


		//Flipper
		if(vexRT[Btn6U]){
			motor[Flipper]=-63;
		}
		if(vexRT[Btn6D]){
			motor[Flipper]=63;
		}
		if(!vexRT[Btn6U]&&!vexRT[Btn6D]){
			if(flipToggle){
				motor[Flipper]=-15;
				}else{
				motor[Flipper]=0;
				}
		}
		if(vexRT[Btn8U]&&flipTime+1000<nSysTime){
			flipToggle=!flipToggle;
			flipTime=nSysTime;
		}
		if(vexRT[Btn8R]&&barTime+1000<nSysTime){
			barToggle=!barToggle;
			barTime=nSysTime;
		}


		//Fourbar
		if(vexRT[Btn5U]){
			motor[FourBar]=127;
		}
		if(vexRT[Btn5D]){
			motor[FourBar]=-127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			if(barToggle){

			motor[FourBar]=15;
		}else{
			motor[FourBar]=0;
		}
	}
}}
