/*#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code generated by Luke                                                             *///

int flipTime=0;
bool flipToggle = false;

int barTime=0;
bool barToggle = false;

task drive(){while(true)
{


		int c1=vexRT[Ch1];
		int c2=vexRT[Ch2];
		int c3=vexRT[Ch3];
		int c4=vexRT[Ch4];

		//Deadzones
		if(abs(c1)<20){c1=0;}
		if(abs(c2)<20){c2=0;}
		if(abs(c3)<20){c3=0;}
		if(abs(c4)<20){c4=0;}

		//Drivetrain
		motor[FrontLeft]=motor[BackLeft]=c3;
		motor[FrontRight]=motor[BackRight]=-c2;


		//Flipper
		if(vexRT[Btn6U]){
			motor[Wrist]=-63;
		}
		if(vexRT[Btn6D]){
			motor[Wrist]=63;
		}if(!vexRT[Btn6U]&&!vexRT[Btn6D]){
		motor[Wrist]=0;
	}



		//Fourbar
		if(vexRT[Btn5U]){
			motor[DR4BLeft]=127;
			motor[DR4BRight]=-127;
		}
		if(vexRT[Btn5D]){
			motor[DR4BLeft]=-127;
			motor[DR4BRight]=127;
		}
		if(!vexRT[Btn5U]&&!vexRT[Btn5D]){
			motor[DR4BLeft]=0;
			motor[DR4BRight]=0;
		}
}}
